<?php

namespace Jad\Serializers;

use Jad\Map\Mapper;
use Jad\Map\MapItem;
use Jad\Exceptions\JadException;
use Tobscure\JsonApi\AbstractSerializer;
use Tobscure\JsonApi\Collection;
use Tobscure\JsonApi\Resource;
use Tobscure\JsonApi\Relationship;
use Doctrine\ORM\PersistentCollection;

class EntitySerializer extends AbstractSerializer
{
    const DATE_FORMAT = 'Y-m-d';
    const TIME_FORMAT = 'H:i:s';
    const DATE_TIME_FORMAT = self::DATE_FORMAT . ' ' . self::TIME_FORMAT;

    /**
     * @var Mapper $mapper
     */
    protected $mapper;

    /**
     * EntitySerializer constructor.
     * @param Mapper $mapper
     * @param $type
     */
    public function __construct(Mapper $mapper, $type)
    {
        $this->mapper = $mapper;
        $this->type = $type;
    }

    /**
     * @return MapItem
     * @throws JadException
     */
    public function getMapItem(): MapItem
    {
        $mapItem = $this->mapper->getMapItem($this->type);

        if(!$mapItem instanceof MapItem) {
            throw new JadException('Could not find map item for type: ' . $this->type);
        }

        return $mapItem;
    }

    /**
     * @param mixed $entity
     * @return mixed
     * @throws JadException
     */
    public function getId($entity): int
    {
        return $this->getPropertyValue($entity, $this->getMapItem()->getIdField());
    }

    /**
     * @param mixed $entity
     * @param array|null $fields
     * @return array
     */
    public function getAttributes($entity, array $fields = null)
    {
        $attributes = [];

        foreach($this->getMapItem()->getClassMeta()->getFieldNames() as $field) {
            if($field === $this->getMapItem()->getIdField()) {
                continue;
            }
            $value = $this->normalizeValue($this->getPropertyValue($entity, $field));
            $attributes[$field] = $value;
        }

        return $attributes;
    }

    /**
     * @param mixed $model
     * @return string
     */
    public function getType($model)
    {
        return $this->getMapItem()->getType();
    }

    public function getLinks($entity)
    {
        return parent::getLinks($entity); // TODO: Change the autogenerated stub
    }

    public function getMeta($entity)
    {
        return parent::getMeta($entity); // TODO: Change the autogenerated stub
    }

    /**
     * @param mixed $entity
     * @param string $type
     * @return Relationship
     * @throws JadException
     */
    public function getRelationship($entity, $type)
    {
        if(!$this->mapper->hasMapItem($type)) {
            return null;
        }

        if (!$this->getMapItem()->getClassMeta()->hasAssociation($type)) {
            throw new JadException('Cannot find relationship/association for fields: ' . $type . '/s');
        }

        $method = 'get' . ucfirst($type);

        if (!method_exists($entity, $method)) {
            throw new JadException('Fetching relationship/association, method does not exists: ' . $method . '/s');
        } else {
            $result = $entity->$method();
        }

        if($result instanceof PersistentCollection) {
            $element = new Collection($result, new self($this->mapper, $type));
        } else {
            $element = new Resource($result, new self($this->mapper, $type));
        }

        $relationship = new Relationship($element);
        $relationship->addLink('related', 'path');

        return $relationship;
    }

    /**
     * @param $entity
     * @param $property
     * @return mixed
     * @throws JadException
     */
    private function getPropertyValue($entity, $property)
    {
        $methodName = 'get' . ucfirst($property);

        if(method_exists($entity, $methodName)) {
            return $entity->$methodName();
        }

        $reflection = new \ReflectionClass($entity);

        if($reflection->hasProperty($property)) {
            $reflectionProperty = $reflection->getProperty($property);
            $reflectionProperty->isPublic();
            $reflectionProperty->setAccessible(true);
            return $reflectionProperty->getValue($entity);
        }

        throw new JadException('Unable to get property "' . $property . '" of ' . $this->getMapItem()->getType());
    }

    /**
     * @param $value
     * @return string
     */
    private function normalizeValue($value)
    {
        if($value instanceof \DateTime) {
            return $value->format(self::DATE_TIME_FORMAT);
        }

        return $value;
    }
}