<?php

namespace Jad;

use Jad\Exceptions\JadException;
use Doctrine\ORM\Mapping\ClassMetadata;
use Tobscure\JsonApi\AbstractSerializer;

class Serializer extends AbstractSerializer
{
    const ID_PROPERTY = 'id';
    const DATE_FORMAT = 'Y-m-d';
    const TIME_FORMAT = 'H:i:s';
    const DATE_TIME_FORMAT = self::DATE_FORMAT . ' ' . self::TIME_FORMAT;

    /**
     * @var string
     */
    protected $type = 'undefined';

    /**
     * @var ClassMetadata $classMeta
     */
    protected $classMeta;

    /**
     * Serializer constructor.
     * @param $type
     * @param ClassMetadata $classMetadata
     */
    public function __construct($type, ClassMetadata $classMetadata)
    {
        $this->type = $type;
        $this->classMeta = $classMetadata;
    }

    /**
     * @param mixed $entity
     * @return mixed
     * @throws JadException
     */
    public function getId($entity): int
    {
        return $this->getPropertyValue($entity, self::ID_PROPERTY);
    }

    /**
     * @param mixed $entity
     * @param array|null $fields
     * @return array
     */
    public function getAttributes($entity, array $fields = null)
    {
        $attributes = [];

        foreach($this->classMeta->getFieldNames() as $field) {
            if($field === self::ID_PROPERTY) {
                continue;
            }
            $value = $this->normalizeValue($this->getPropertyValue($entity, $field));
            $attributes[$field] = $value;
        }

        return $attributes;
    }

    public function getLinks($entity)
    {
        return parent::getLinks($entity); // TODO: Change the autogenerated stub
    }

    public function getMeta($entity)
    {
        return parent::getMeta($entity); // TODO: Change the autogenerated stub
    }

    public function getRelationship($entity, $name)
    {
        return parent::getRelationship($entity, $name); // TODO: Change the autogenerated stub
    }

    /**
     * @param $entity
     * @param $property
     * @return mixed
     * @throws JadException
     */
    private function getPropertyValue($entity, $property)
    {
        $methodName = 'get' . ucfirst($property);

        if(method_exists($entity, $methodName)) {
            return $entity->$methodName();
        }

        $reflection = new \ReflectionClass($entity);

        if($reflection->hasProperty($property)) {
            $reflectionProperty = $reflection->getProperty($property);
            $reflectionProperty->isPublic();
            $reflectionProperty->setAccessible(true);
            return $reflectionProperty->getValue($entity);
        }

        throw new JadException('Unable to get property "' . $property . '" of ' . $this->type);
    }

    /**
     * @param $value
     * @return string
     */
    private function normalizeValue($value)
    {
        if($value instanceof \DateTime) {
            return $value->format(self::DATE_TIME_FORMAT);
        }

        return $value;
    }
}